In [1]:
import numpy as np

Задание 1.

In [9]:
m = np.random.rand(10,3)
print(m)
print(m.reshape(1,30)[0,abs(a-0.5).argmin(axis = 1) + np.arange(10)*3])

[[0.00186665 0.85130101 0.79976378]
 [0.45429175 0.04784478 0.45598514]
 [0.94126488 0.25267435 0.99340521]
 [0.0940556  0.12553653 0.97376388]
 [0.47034206 0.04647732 0.78232689]
 [0.02196244 0.4106656  0.36611098]
 [0.34493707 0.05640831 0.01660785]
 [0.2823913  0.82339361 0.71470721]
 [0.40655393 0.57725984 0.56043832]
 [0.92986275 0.78278345 0.24783687]]
[0.00186665 0.45429175 0.94126488 0.12553653 0.04647732 0.4106656
 0.34493707 0.2823913  0.56043832 0.24783687]


Задание 2.

In [11]:
a = np.random.rand(6,6)
a.sum(axis = 0)/a.min(axis = 1)

array([12.56027328, 39.84077746, 46.21091076, 28.6741331 , 86.59097233,
       10.73241647])

Задание 3.

In [14]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
x[(x == 0)[np.concatenate(((np.arange(8)+1), [False]))]].max()

7

Задание 4.

In [20]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
z = np.zeros(80)
z[i + np.arange(8)*10] = 1
x + z.reshape(8,10).sum(axis = 0)

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

Задание 5.

In [21]:
a = np.arange(16).reshape(4, 4)
row, col = np.indices((4,4))
dictionary = {i: a[row + col == i] for i in range (7)}
dictionary

{0: array([0]),
 1: array([1, 4]),
 2: array([2, 5, 8]),
 3: array([ 3,  6,  9, 12]),
 4: array([ 7, 10, 13]),
 5: array([11, 14]),
 6: array([15])}

Задание 6.

In [26]:
def get_labels(X, centroids):
    return np.argmin(np.linalg.norm(X - centroids[:, None], axis = 2), axis = 0)
def algorithm(obs,k, iter, thresh):
    
    centroids = X[0:k]
    l=0
    labels = get_labels(X,centroids)
    distortion = 1
    memory = distortion + 1
    while ((np.linalg.norm(memory - distortion))>thresh):
        l += 1
        memory = distortion
        if(l == iter):break
        labels = get_labels(X,centroids)
        for i in range(k):
            mask = labels == i
            centroids[i] = np.mean(X[mask],axis = 0)
        distortion = np.sum(np.linalg.norm(obs - centroids[labels], axis = 0))
    
    return centroids, distortion
centroid = np.array([[5, 5], [10, 10]])

X = np.repeat(centroid, 5, axis = 0)
X = X + np.random.randn(*X.shape)
algorithm(X,3,30,1e-12)

(array([[ 5.39810931,  5.90202355],
        [10.23502976,  9.85151526],
        [ 3.3656022 ,  5.34099194]]), 4.718843917873826)